---
- name: Get a busybox image using ansible
  hosts:  all
  become: true
  tasks:
    - name: Get the image with docker_container command
      docker_container:
        name: mydata
        image: busybox
        volumes:
          - /data
...

